# Generated by Django 6.1 on 2026-08-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kycsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='method',
            field=models.CharField(choices=[('DOCUMENT', 'Document upload'), ('AADHAAR_OTP', 'Aadhaar OTP')], default='DOCUMENT', max_length=15),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='provider_reference_id',
            field=models.CharField(blank=True, help_text="The KYC provider's transaction/reference ID for an Aadhaar OTP attempt (audit trail only).", max_length=100),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='document',
            field=models.FileField(blank=True, help_text='Required for document-upload submissions. Not used for Aadhaar OTP.', null=True, upload_to='kyc/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='id_last4',
            field=models.CharField(help_text='Last 4 characters/digits of the ID number only. Never store the full number.', max_length=4),
        ),
    ]
