# Generated by Django 6.1 on 2026-08-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_remove_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='rental_amount',
            new_name='rental_price',
        ),
    ]
