# Generated by Django 6.1 on 2026-08-22 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_rental_amount_booking_rental_price'),
        ('products', '0004_delete_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='deposit_amount',
            new_name='security_deposit',
        ),
        migrations.AlterField(
            model_name='booking',
            name='lender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='products.product'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renter_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Awaiting Lender Approval'), ('APPROVED', 'Approved (Awaiting Payment)'), ('PAID', 'Paid (Awaiting Handover)'), ('ACTIVE', 'Active (Item Handed Over)'), ('COMPLETED', 'Completed (Returned & Settled)'), ('REJECTED', 'Rejected by Lender'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20),
        ),
    ]
