# Generated by Django 6.1 on 2026-08-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_booking_rental_fee_booking_security_deposit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
