# Generated by Django 4.2.11 on 2026-08-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vehicles', 'Cars, Bikes & Vehicles'), ('Electronics', 'Electronics & Appliances'), ('Mobiles', 'Mobiles & Tablets'), ('Furniture', 'Furniture & Decor'), ('Fashion', 'Fashion & Clothing'), ('Books & Sports', 'Books, Sports & Hobbies'), ('Tools', 'Tools & Machinery'), ('Outdoors', 'Outdoors & Camping'), ('Entertainment', 'Gaming & Entertainment'), ('Properties', 'Real Estate & Properties'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
